CycleLog/CycleLog.MVC/Models/ErrorViewModel.cs
namespace CycleLog.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CycleLog/CycleLog.MVC/Controllers/HomeController.cs
using CycleLog.ApiClient.Interfaces;
using CycleLog.MVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CycleLog.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ITrainingSessionApiClient _trainingSessionApiClient;

        public HomeController(ILogger<HomeController> logger, ITrainingSessionApiClient trainingSessionApiClient)
        {
            _logger = logger;
            _trainingSessionApiClient = trainingSessionApiClient;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _trainingSessionApiClient.GetLeaderboardAsync());
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        [Authorize]
        public async Task<IActionResult> Login()
        {
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Logout()
        {
            var redirectUri = Url.Action("Index", "Home", null, Request.Scheme);

            return SignOut(new AuthenticationProperties
            {
                RedirectUri = redirectUri
            },
            CookieAuthenticationDefaults.AuthenticationScheme,
            OpenIdConnectDefaults.AuthenticationScheme);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CycleLog/CycleLog.MVC/Controllers/TrainingSessionController.cs
using CycleLog.ApiClient.Interfaces;
using CycleLog.DAL.DTO;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;
using System.Security.Claims;

namespace CycleLog.MVC.Controllers
{
    public class TrainingSessionController : Controller
    {
        private readonly ILogger<TrainingSessionController> _logger;
        private readonly ITrainingSessionApiClient _trainingSessionApiClient;

        public TrainingSessionController(ILogger<TrainingSessionController> logger, ITrainingSessionApiClient trainingSessionApiClient)
        {
            _logger = logger;
            _trainingSessionApiClient = trainingSessionApiClient;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                string accessToken = await HttpContext.GetTokenAsync("access_token");

                return View(await _trainingSessionApiClient.GetTrainingSessionsByUserIdAsync(userId, accessToken));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create([FromForm] TrainingSessionDTO trainingSession)
        {
            try
            {
                //TODO: Denne metode er ikke færdig!
                string accessToken = await HttpContext.GetTokenAsync("access_token");

                int newId = await _trainingSessionApiClient.CreateTrainingSessionAsync(trainingSession, accessToken);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }
    }
}

CycleLog/CycleLog.MVC/Views/Home/Index.cshtml
@model IEnumerable<CycleLog.DAL.DTO.TrainingSessionDTO>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">CycleLog</h1>
    <p>Velkommen til CycleLog - her kan du registrere dine træninger og konkurrere mod andre ryttere.</p>
</div>

<div class="cta-container">
    @if (User.Identity.IsAuthenticated)
    {
        <a class="btn-primary" href="@Url.Action("Create", "TrainingSession")">
            Indberet ny træning
        </a>
    }
    else
    {
        <a class="btn-primary" href="@Url.Action("Login", "Home")">
            Login
        </a>
    }
</div>

<div class="leaderboard">
    <table>
        <thead>
            <tr>
                <th>Place</th>
                <th>Name</th>
                <th>Total Distance</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>Place</td>
                <td>@item.Username</td>
                <td>@item.DistanceKm Km</td>
            </tr>
        }
    </table>
</div>

CycleLog/CycleLog.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CycleLog.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CycleLog.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CycleLog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Forside</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TrainingSession" asp-action="Index">Mine træninger</a> 
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CycleLog.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CycleLog/CycleLog.MVC/Views/TrainingSession/Create.cshtml
@model CycleLog.DAL.DTO.TrainingSessionDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TrainingSessionDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DistanceKm" class="control-label"></label>
                <input asp-for="DistanceKm" class="form-control" />
                <span asp-validation-for="DistanceKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AverageSpeed" class="control-label"></label>
                <input asp-for="AverageSpeed" class="form-control" />
                <span asp-validation-for="AverageSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input type="time" step="1" asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--IsIndoor is currently always set to true. Label is removed since the user can't input anything-->
                <!--<label asp-for="IsIndoor" class="control-label"></label>-->
                <input type="hidden" value="true" asp-for="IsIndoor" class="form-control" />
                <span asp-validation-for="IsIndoor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CycleLog/CycleLog.MVC/Views/TrainingSession/Index.cshtml
@model IEnumerable<CycleLog.DAL.DTO.TrainingSessionDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Mine træninger</h1>

<p>
    <a asp-action="Create">Indberet ny træning</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DistanceKm)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AverageSpeed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsIndoor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DistanceKm)
            </td>
            <td>
                @Html.DisplayFor(modeItem => item.AverageSpeed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsIndoor)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>